"""
Anhangsprüfer - Audit Support Tool for Notes to Financial Statements

IMPORTANT DISCLAIMER:
This tool provides audit SUPPORT functionality only. It does NOT perform
a UGB-compliant audit. All assessments generated by this tool require
professional review and validation by a qualified auditor. Final legal
and professional judgment must remain with the auditor.

This software is designed to assist in the structured review of notes
to the financial statements (Anhang) under Austrian commercial law (UGB),
specifically §§ 236-243 UGB.
"""

__version__ = "1.0.0"
__author__ = "Audit Support Tool Development"

DISCLAIMER = """
================================================================================
HAFTUNGSAUSSCHLUSS / DISCLAIMER
================================================================================
Dieses Tool dient ausschließlich der Prüfungsunterstützung und ersetzt NICHT
die fachliche Beurteilung durch einen qualifizierten Wirtschaftsprüfer.

Alle automatisch generierten Bewertungen und Feststellungen sind als vorläufige
Arbeitsergebnisse zu verstehen, die einer manuellen Überprüfung und Validierung
durch den verantwortlichen Prüfer bedürfen.

Die endgültige rechtliche und fachliche Beurteilung obliegt ausschließlich
dem Abschlussprüfer.
================================================================================
"""
